import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
  OneToMany,
  type Relation,
} from 'typeorm';
import type { SpatialFeature } from './spatial-feature.entity';

export enum GeometryType {
  POINT              = 'point',
  LINESTRING         = 'linestring',
  POLYGON            = 'polygon',
  MULTIPOINT         = 'multipoint',
  MULTILINESTRING    = 'multilinestring',
  MULTIPOLYGON       = 'multipolygon',
  GEOMETRY_COLLECTION = 'geometry_collection',
  RASTER             = 'raster',
}

export enum UpdateCadence {
  REAL_TIME = 'real_time',
  HOURLY    = 'hourly',
  DAILY     = 'daily',
  WEEKLY    = 'weekly',
  MONTHLY   = 'monthly',
  ON_DEMAND = 'on_demand',
  STATIC    = 'static',
}

export enum LayerStatus {
  ACTIVE     = 'active',
  DRAFT      = 'draft',
  DEPRECATED = 'deprecated',
  ARCHIVED   = 'archived',
}

export enum QualityStatus {
  UNVALIDATED  = 'unvalidated',
  VALID        = 'valid',
  INVALID      = 'invalid',
  NEEDS_REVIEW = 'needs_review',
}

@Entity({ name: 'spatial_layers', schema: 'gis' })
@Index(['status'])
@Index(['geometryType'])
@Index(['classification'])
export class SpatialLayer {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ length: 200 })
  name: string;

  @Column({ type: 'text', nullable: true })
  description: string | null;

  @Column({
    name: 'geometry_type',
    type: 'enum',
    enum: GeometryType,
    enumName: 'geometry_type',
  })
  geometryType: GeometryType;

  @Column({ type: 'int', default: 4326 })
  srid: number;

  /** 0=unrestricted 1=internal 2=confidential 3=secret */
  @Column({ type: 'smallint', default: 0 })
  classification: number;

  @Column({ name: 'owner_position_id', type: 'uuid' })
  ownerPositionId: string;

  @Column({
    name: 'update_cadence',
    type: 'enum',
    enum: UpdateCadence,
    enumName: 'update_cadence',
    default: UpdateCadence.ON_DEMAND,
  })
  updateCadence: UpdateCadence;

  @Column({
    type: 'enum',
    enum: LayerStatus,
    enumName: 'layer_status',
    default: LayerStatus.DRAFT,
  })
  status: LayerStatus;

  @Column({
    name: 'quality_status',
    type: 'enum',
    enum: QualityStatus,
    enumName: 'quality_status',
    default: QualityStatus.UNVALIDATED,
  })
  qualityStatus: QualityStatus;

  @Column({ name: 'last_validated_at', type: 'timestamptz', nullable: true })
  lastValidatedAt: Date | null;

  @Column({ type: 'varchar',  name: 'source_name', length: 300, nullable: true })
  sourceName: string | null;

  @Column({ name: 'source_url', type: 'text', nullable: true })
  sourceUrl: string | null;

  @Column({ type: 'text', array: true, default: '{}' })
  keywords: string[];

  /** Attribute field definitions [{ name, type, required, description }] */
  @Column({ name: 'schema_definition', type: 'jsonb', nullable: true })
  schemaDefinition: object | null;

  /** MapLibre GL style specification for client-side rendering */
  @Column({ type: 'jsonb', nullable: true })
  symbology: object | null;

  @Column({ name: 'feature_count', type: 'int', default: 0 })
  featureCount: number;

  /** Layer bounding box as GeoJSON */
  @Column({ name: 'extent_geojson', type: 'jsonb', nullable: true })
  extentGeojson: object | null;

  @Column({ name: 'retention_days', type: 'int', nullable: true })
  retentionDays: number | null;

  @Column({ name: 'published_at', type: 'timestamptz', nullable: true })
  publishedAt: Date | null;

  @Column({ name: 'deprecated_at', type: 'timestamptz', nullable: true })
  deprecatedAt: Date | null;

  // ── AI/ML risk layer fields (§12.1) ──────────────────────────────────────

  /** True if this layer was generated by an ML prediction run */
  @Column({ name: 'is_ai_generated', default: false })
  isAiGenerated: boolean;

  /** ID of the RiskPrediction batch that produced this layer */
  @Column({ name: 'source_prediction_id', type: 'uuid', nullable: true })
  sourcePredictionId: string | null;

  /** Hazard type of the AI model that produced this layer */
  @Column({ name: 'ai_hazard_type', length: 50, nullable: true })
  aiHazardType: string | null;

  /** When the AI model ran and produced this layer */
  @Column({ name: 'ai_generated_at', type: 'timestamptz', nullable: true })
  aiGeneratedAt: Date | null;

  /** When the prediction output expires (after which the layer becomes stale) */
  @Column({ name: 'prediction_valid_until', type: 'timestamptz', nullable: true })
  predictionValidUntil: Date | null;

  /** Analyst who reviewed and approved this AI-generated layer */
  @Column({ name: 'ai_approved_by_id', type: 'uuid', nullable: true })
  aiApprovedById: string | null;

  /** When the AI layer was approved by an analyst */
  @Column({ name: 'ai_approved_at', type: 'timestamptz', nullable: true })
  aiApprovedAt: Date | null;

  /** Rejection reason if an analyst rejected this AI-generated layer */
  @Column({ name: 'ai_rejection_reason', type: 'text', nullable: true })
  aiRejectionReason: string | null;

  @Column({ name: 'created_by_id', type: 'uuid' })
  createdById: string;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt: Date;

  @OneToMany('SpatialFeature', 'layer')
  features: Relation<SpatialFeature[]>;
}
