import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Adds AI/ML prediction layer tracking fields to gis.spatial_layers.
 *
 * §12.1 — Risk Layer Publication Workflow: AI model outputs enter the GIS
 * platform as DRAFT layers pending analyst review before becoming OPERATIONAL.
 * These columns track the lineage and review state of AI-generated layers.
 */
export class GisAiLayerEnhancements1712300040000 implements MigrationInterface {
  name = 'GisAiLayerEnhancements1712300040000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE gis.spatial_layers
        ADD COLUMN IF NOT EXISTS is_ai_generated        BOOLEAN       NOT NULL DEFAULT FALSE,
        ADD COLUMN IF NOT EXISTS source_prediction_id   UUID          NULL,
        ADD COLUMN IF NOT EXISTS ai_hazard_type         VARCHAR(50)   NULL,
        ADD COLUMN IF NOT EXISTS ai_generated_at        TIMESTAMPTZ   NULL,
        ADD COLUMN IF NOT EXISTS prediction_valid_until TIMESTAMPTZ   NULL,
        ADD COLUMN IF NOT EXISTS ai_approved_by_id      UUID          NULL,
        ADD COLUMN IF NOT EXISTS ai_approved_at         TIMESTAMPTZ   NULL,
        ADD COLUMN IF NOT EXISTS ai_rejection_reason    TEXT          NULL
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_spatial_layers_ai_generated
        ON gis.spatial_layers (is_ai_generated, status)
        WHERE is_ai_generated = TRUE
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_spatial_layers_prediction_id
        ON gis.spatial_layers (source_prediction_id)
        WHERE source_prediction_id IS NOT NULL
    `);

    await queryRunner.query(`
      COMMENT ON COLUMN gis.spatial_layers.is_ai_generated IS
        'True if this layer was generated by an ML prediction run (§12.1).'
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN gis.spatial_layers.source_prediction_id IS
        'References ml.risk_predictions.id — the batch that produced this layer.'
    `);
    await queryRunner.query(`
      COMMENT ON COLUMN gis.spatial_layers.prediction_valid_until IS
        'When the AI prediction expires; layer transitions to stale after this time.'
    `);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS gis.idx_spatial_layers_prediction_id`);
    await queryRunner.query(`DROP INDEX IF EXISTS gis.idx_spatial_layers_ai_generated`);
    await queryRunner.query(`
      ALTER TABLE gis.spatial_layers
        DROP COLUMN IF EXISTS is_ai_generated,
        DROP COLUMN IF EXISTS source_prediction_id,
        DROP COLUMN IF EXISTS ai_hazard_type,
        DROP COLUMN IF EXISTS ai_generated_at,
        DROP COLUMN IF EXISTS prediction_valid_until,
        DROP COLUMN IF EXISTS ai_approved_by_id,
        DROP COLUMN IF EXISTS ai_approved_at,
        DROP COLUMN IF EXISTS ai_rejection_reason
    `);
  }
}
